<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hugin_launch</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="niklas.digakis@studmail.w-hs.de">ndigakis</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>rosbag2_transport</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>mavros</exec_depend>
  <exec_depend>dai_vi_ros2</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>virtcam</exec_depend>
  <exec_depend>image_gst</exec_depend>
  <exec_depend>gstreamer1.0-plugins-good</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
